# -*- coding: utf-8 -*-
"""Credit_Transition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WJ-81ptjAlcl7wGEGyaTVjyWlEkD10Dq
"""

"""
Generalizes the Moody's-only validation to run BOTH agencies:
loads each agency's 1-year matrix, cubes it, compares against their own
published 3-year matrix. Same modeling assumption as before: Paid Off and
Withdrawn (other) are excluded and each row is renormalized over
{ratings, Default} only, since those two columns aren't credit events and
including them would break the closed-system requirement for matrix power.
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# --- Rating scales, in order from safest to riskiest ---
MOODYS_ORDER = [
    "Aaa", "Aa1", "Aa2", "Aa3", "A1", "A2", "A3", "Baa1", "Baa2", "Baa3",
    "Ba1", "Ba2", "Ba3", "B1", "B2", "B3", "Caa1", "Caa2", "Caa3", "Ca", "C",
]

SP_ORDER = [
    "AAA", "AA+", "AA", "AA-", "A+", "A", "A-", "BBB+", "BBB", "BBB-",
    "BB+", "BB", "BB-", "B+", "B", "B-", "CCC+", "CCC", "CCC-", "CC", "C",
]

# --- Where to load the CSVs from ---
# Reading directly from your GitHub repo, not a local file — this way
# Colab doesn't need any manual upload step.
GITHUB_BASE = "."


def load_matrix(csv_path, rating_order):
    """Turns a benchmark CSV into a square Markov transition matrix."""
    df = pd.read_csv(csv_path).set_index("starting_rating")

    states = [r for r in rating_order if r in df.index] + ["Default"]
    n = len(states)
    M = np.zeros((n, n))

    keep_cols = [c for c in rating_order if c in df.columns] + ["Default"]

    for i, start in enumerate(states):
        if start == "Default":
            M[i, i] = 1.0  # Default is absorbing: once there, stay there
            continue
        row = df.loc[start]
        vals = row[keep_cols].astype(float).values
        total = vals.sum()
        if total > 0:
            vals = vals / total * 100  # renormalize over kept states only
        for j, target in enumerate(states):
            idx = keep_cols.index(target)
            M[i, j] = vals[idx] / 100

    return M, states


def matrix_to_df(M, states):
    return pd.DataFrame(M * 100, index=states, columns=states).round(2)


def validate_agency(agency_name, order, file_prefix):
    """Runs the full 1yr-cubed vs 3yr-actual comparison for one agency."""
    print(f"\n{'='*60}\n{agency_name}\n{'='*60}")

    M1, states = load_matrix(f"{GITHUB_BASE}/{file_prefix}_corporate_1y.csv", order)
    M3_predicted = np.linalg.matrix_power(M1, 3)
    predicted_df = matrix_to_df(M3_predicted, states)

    M3_actual, states_actual = load_matrix(f"{GITHUB_BASE}/{file_prefix}_corporate_3y.csv", order)
    actual_df = matrix_to_df(M3_actual, states_actual)

    diff_df = (predicted_df - actual_df).round(2)

    diag_compare = pd.DataFrame({
        "predicted_1y_cubed": np.diag(predicted_df.values),
        "actual_3y": np.diag(actual_df.values),
    }, index=states)
    diag_compare["abs_diff"] = (diag_compare["predicted_1y_cubed"] - diag_compare["actual_3y"]).abs()

    print(diag_compare.round(1))
    print(f"\nMean absolute difference (all cells): {diff_df.abs().values.mean():.2f} pp")
    print(f"Max absolute difference: {diff_df.abs().values.max():.2f} pp")

    # Plot
    fig, axes = plt.subplots(1, 2, figsize=(20, 9))
    for ax, df, subtitle in zip(axes, [predicted_df, actual_df],
                                  ["Predicted (1yr)^3", "Actual published 3-year"]):
        im = ax.imshow(df.values, cmap="Blues", vmin=0, vmax=100)
        ax.set_xticks(range(len(df.columns))); ax.set_xticklabels(df.columns, rotation=90, fontsize=7)
        ax.set_yticks(range(len(df.index))); ax.set_yticklabels(df.index, fontsize=7)
        ax.set_title(subtitle, fontsize=11)
        for i in range(len(df.index)):
            for j in range(len(df.columns)):
                v = df.values[i, j]
                if v > 3:
                    ax.text(j, i, f"{v:.0f}", ha="center", va="center", fontsize=6,
                            color="white" if v > 50 else "black")
    fig.suptitle(f"{agency_name} Corporate Issuers: (1-Year)^3 vs. Actual 3-Year", fontsize=13)
    fig.tight_layout()
    fig.savefig(f"{file_prefix}_1y_cubed_vs_3y_actual.png", dpi=150, bbox_inches="tight")
    plt.show()

    return predicted_df, actual_df, diff_df, diag_compare


# --- Run for both agencies ---
moodys_predicted, moodys_actual, moodys_diff, moodys_diag = validate_agency(
    "Moody's", MOODYS_ORDER, "moodys"
)
sp_predicted, sp_actual, sp_diff, sp_diag = validate_agency(
    "S&P", SP_ORDER, "sp"
)

# --- Save all outputs as CSVs (Colab will let you download these) ---
moodys_predicted.to_csv("moodys_predicted_3y_from_1y_cubed.csv")
moodys_actual.to_csv("moodys_actual_3y_renormalized.csv")
moodys_diff.to_csv("moodys_1y3_vs_actual_3y_diff.csv")
moodys_diag.to_csv("moodys_diagonal_comparison.csv")

sp_predicted.to_csv("sp_predicted_3y_from_1y_cubed.csv")
sp_actual.to_csv("sp_actual_3y_renormalized.csv")
sp_diff.to_csv("sp_1y3_vs_actual_3y_diff.csv")
sp_diag.to_csv("sp_diagonal_comparison.csv")

print("\nAll files saved. In Colab, download them from the file browser on the left.")

import pandas as pd
test = pd.read_csv("https://raw.githubusercontent.com/vedshreez/credit-transition-matrix/main/data/moodys_corporate_1y.csv")
print(test.head())

"""
Runs BOTH agencies: loads each agency's 1-year matrix, cubes it, compares
against their own published 3-year matrix.
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

MOODYS_ORDER = [
    "Aaa", "Aa1", "Aa2", "Aa3", "A1", "A2", "A3", "Baa1", "Baa2", "Baa3",
    "Ba1", "Ba2", "Ba3", "B1", "B2", "B3", "Caa1", "Caa2", "Caa3", "Ca", "C",
]

SP_ORDER = [
    "AAA", "AA+", "AA", "AA-", "A+", "A", "A-", "BBB+", "BBB", "BBB-",
    "BB+", "BB", "BB-", "B+", "B", "B-", "CCC+", "CCC", "CCC-", "CC", "C",
]

GITHUB_BASE = "https://raw.githubusercontent.com/vedshreez/credit-transition-matrix/main/data"


def load_matrix(csv_path, rating_order):
    df = pd.read_csv(csv_path).set_index("starting_rating")
    states = [r for r in rating_order if r in df.index] + ["Default"]
    n = len(states)
    M = np.zeros((n, n))
    keep_cols = [c for c in rating_order if c in df.columns] + ["Default"]

    for i, start in enumerate(states):
        if start == "Default":
            M[i, i] = 1.0
            continue
        row = df.loc[start]
        vals = row[keep_cols].astype(float).values
        total = vals.sum()
        if total > 0:
            vals = vals / total * 100
        for j, target in enumerate(states):
            idx = keep_cols.index(target)
            M[i, j] = vals[idx] / 100

    return M, states


def matrix_to_df(M, states):
    return pd.DataFrame(M * 100, index=states, columns=states).round(2)


def validate_agency(agency_name, order, file_prefix):
    print(f"\n{'='*60}\n{agency_name}\n{'='*60}")

    M1, states = load_matrix(f"{GITHUB_BASE}/{file_prefix}_corporate_1y.csv", order)
    M3_predicted = np.linalg.matrix_power(M1, 3)
    predicted_df = matrix_to_df(M3_predicted, states)

    M3_actual, states_actual = load_matrix(f"{GITHUB_BASE}/{file_prefix}_corporate_3y.csv", order)
    actual_df = matrix_to_df(M3_actual, states_actual)

    diff_df = (predicted_df - actual_df).round(2)

    diag_compare = pd.DataFrame({
        "predicted_1y_cubed": np.diag(predicted_df.values),
        "actual_3y": np.diag(actual_df.values),
    }, index=states)
    diag_compare["abs_diff"] = (diag_compare["predicted_1y_cubed"] - diag_compare["actual_3y"]).abs()

    print(diag_compare.round(1))
    print(f"\nMean absolute difference (all cells): {diff_df.abs().values.mean():.2f} pp")
    print(f"Max absolute difference: {diff_df.abs().values.max():.2f} pp")

    fig, axes = plt.subplots(1, 2, figsize=(20, 9))
    for ax, df, subtitle in zip(axes, [predicted_df, actual_df],
                                  ["Predicted (1yr)^3", "Actual published 3-year"]):
        im = ax.imshow(df.values, cmap="Blues", vmin=0, vmax=100)
        ax.set_xticks(range(len(df.columns))); ax.set_xticklabels(df.columns, rotation=90, fontsize=7)
        ax.set_yticks(range(len(df.index))); ax.set_yticklabels(df.index, fontsize=7)
        ax.set_title(subtitle, fontsize=11)
        for i in range(len(df.index)):
            for j in range(len(df.columns)):
                v = df.values[i, j]
                if v > 3:
                    ax.text(j, i, f"{v:.0f}", ha="center", va="center", fontsize=6,
                            color="white" if v > 50 else "black")
    fig.suptitle(f"{agency_name} Corporate Issuers: (1-Year)^3 vs. Actual 3-Year", fontsize=13)
    fig.tight_layout()
    fig.savefig(f"{file_prefix}_1y_cubed_vs_3y_actual.png", dpi=150, bbox_inches="tight")
    plt.show()

    return predicted_df, actual_df, diff_df, diag_compare


moodys_predicted, moodys_actual, moodys_diff, moodys_diag = validate_agency(
    "Moody's", MOODYS_ORDER, "moodys"
)
sp_predicted, sp_actual, sp_diff, sp_diag = validate_agency(
    "S&P", SP_ORDER, "sp"
)

moodys_predicted.to_csv("moodys_predicted_3y_from_1y_cubed.csv")
moodys_actual.to_csv("moodys_actual_3y_renormalized.csv")
moodys_diff.to_csv("moodys_1y3_vs_actual_3y_diff.csv")
moodys_diag.to_csv("moodys_diagonal_comparison.csv")

sp_predicted.to_csv("sp_predicted_3y_from_1y_cubed.csv")
sp_actual.to_csv("sp_actual_3y_renormalized.csv")
sp_diff.to_csv("sp_1y3_vs_actual_3y_diff.csv")
sp_diag.to_csv("sp_diagonal_comparison.csv")

print("\nAll files saved. In Colab, download them from the file browser on the left.")

"""
Week 2: Baseline (calm, Dec 2024-2025) vs. Stressed (COVID recession,
Dec 2019-2020) comparison of Moody's Corporate Issuers 1-year matrix.
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

MOODYS_ORDER = [
    "Aaa", "Aa1", "Aa2", "Aa3", "A1", "A2", "A3", "Baa1", "Baa2", "Baa3",
    "Ba1", "Ba2", "Ba3", "B1", "B2", "B3", "Caa1", "Caa2", "Caa3", "Ca", "C",
]

GITHUB_BASE = "https://raw.githubusercontent.com/vedshreez/credit-transition-matrix/main/data"


def load_matrix(csv_path, rating_order):
    df = pd.read_csv(csv_path).set_index("starting_rating")
    states = [r for r in rating_order if r in df.index] + ["Default"]
    n = len(states)
    M = np.zeros((n, n))
    keep_cols = [c for c in rating_order if c in df.columns] + ["Default"]

    for i, start in enumerate(states):
        if start == "Default":
            M[i, i] = 1.0
            continue
        row = df.loc[start]
        vals = row[keep_cols].astype(float).values
        total = vals.sum()
        if total > 0:
            vals = vals / total * 100
        for j, target in enumerate(states):
            idx = keep_cols.index(target)
            M[i, j] = vals[idx] / 100

    return M, states


def matrix_to_df(M, states):
    return pd.DataFrame(M * 100, index=states, columns=states).round(2)


M_baseline, states = load_matrix(f"{GITHUB_BASE}/moodys_corporate_1y.csv", MOODYS_ORDER)
baseline_df = matrix_to_df(M_baseline, states)

M_stressed, states_s = load_matrix(f"{GITHUB_BASE}/moodys_corporate_1y_2020_recession.csv", MOODYS_ORDER)
stressed_df = matrix_to_df(M_stressed, states_s)

comparison = pd.DataFrame({
    "baseline_default_%": baseline_df["Default"],
    "stressed_default_%": stressed_df["Default"],
}, index=states)
comparison["default_increase_pp"] = (comparison["stressed_default_%"] - comparison["baseline_default_%"]).round(2)
comparison["default_multiplier"] = (comparison["stressed_default_%"] / comparison["baseline_default_%"].replace(0, np.nan)).round(1)

print("=== Baseline vs. Stressed: Default Probability by Starting Rating ===")
print(comparison)
comparison.to_csv("baseline_vs_stressed_default_comparison.csv")

def downgrade_rate(df, states):
    rates = {}
    for i, rating in enumerate(states[:-1]):
        row = df.loc[rating]
        worse_ratings = states[i+1:-1]
        rates[rating] = row[worse_ratings].sum() if worse_ratings else 0.0
    return pd.Series(rates)

baseline_downgrade = downgrade_rate(baseline_df, states)
stressed_downgrade = downgrade_rate(stressed_df, states)

downgrade_comparison = pd.DataFrame({
    "baseline_downgrade_%": baseline_downgrade,
    "stressed_downgrade_%": stressed_downgrade,
})
downgrade_comparison["increase_pp"] = (downgrade_comparison["stressed_downgrade_%"] - downgrade_comparison["baseline_downgrade_%"]).round(2)

print("\n=== Baseline vs. Stressed: Downgrade Rate (to any lower non-default rating) ===")
print(downgrade_comparison.round(2))
downgrade_comparison.to_csv("baseline_vs_stressed_downgrade_comparison.csv")

fig, axes = plt.subplots(1, 2, figsize=(20, 9))
for ax, df, subtitle in zip(axes, [baseline_df, stressed_df],
                              ["Baseline (Dec 2024-Dec 2025)", "Stressed: COVID Recession (Dec 2019-Dec 2020)"]):
    im = ax.imshow(df.values, cmap="Reds" if "Stressed" in subtitle else "Blues", vmin=0, vmax=100)
    ax.set_xticks(range(len(df.columns))); ax.set_xticklabels(df.columns, rotation=90, fontsize=7)
    ax.set_yticks(range(len(df.index))); ax.set_yticklabels(df.index, fontsize=7)
    ax.set_title(subtitle, fontsize=11)
    for i in range(len(df.index)):
        for j in range(len(df.columns)):
            v = df.values[i, j]
            if v > 3:
                ax.text(j, i, f"{v:.0f}", ha="center", va="center", fontsize=6,
                        color="white" if v > 50 else "black")
fig.suptitle("Moody's Corporate Issuers: Baseline vs. COVID-Stressed 1-Year Transition Matrix", fontsize=13)
fig.tight_layout()
fig.savefig("baseline_vs_stressed_heatmap.png", dpi=150, bbox_inches="tight")
plt.show()

print("\nAll files saved. Download from Colab's file browser.")